name: span_builder
description: Facilitates creation of spans from plain text and provides automated disposal of GestureRecognizers
version: 0.1.0
homepage: https://github.com/eyeem/span_builder

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

